name: device_settings_repository
description: A starting point for Dart libraries or applications.
version: 7.0.0

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ^3.4.3

dependencies:
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  settings_repository:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0
