name: flutter_settings
description: "Iconica Flutter Settings component"
version: 4.0.0

publish_to: "none"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  page_view_indicators: ^2.0.0
  shared_preferences: ^2.0.7  
  intl: ^0.18.1
  flutter_profile:
    git:
      url: https://github.com/Iconica-Development/flutter_profile
      ref: 1.5.0
  flutter_input_library:
    git:
      url: https://github.com/Iconica-Development/flutter_input_library
      ref: 3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 6.0.0

flutter:
