name: flutter_settings
description: "A new Flutter package project."
version: 7.0.0
homepage: https://github.com/Iconica-Development?view_as=public

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  intl: any
  settings_repository:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0
  flutter_iconica_utilities:
    version: ^0.5.0
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0
