name: firebase_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_settings:
    path: ../../packages/flutter_settings
  settings_repository:
    path: ../../packages/settings_repository
  firebase_settings_repository:
    path: ../../packages/firebase_settings_repository
  image_picker: ^1.1.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^7.0.0

flutter:
  uses-material-design: true
